version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      # Check for npm updates on Sundays
      day: "sunday"
    # Raise pull requests for version updates
    # to pip against the `develop-4` branch
    target-branch: "develop-4"
  - package-ecosystem: "gomod"
    # directory required https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#vendor
    directory: "/"
    target-branch: "develop-4"
    schedule:
      interval: "monthly"
    # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "monthly"
    target-branch: "develop-4"
