from pyrevit.framework import Windows

DEFAULT_CMDSWITCHWND_WIDTH = 600
DEFAULT_SEARCHWND_WIDTH = 600
DEFAULT_SEARCHWND_HEIGHT = 100
DEFAULT_INPUTWINDOW_WIDTH = 500
DEFAULT_INPUTWINDOW_HEIGHT = 600
DEFAULT_RECOGNIZE_ACCESS_KEY = False

WPF_HIDDEN = Windows.Visibility.Hidden
WPF_COLLAPSED = Windows.Visibility.Collapsed
WPF_VISIBLE = Windows.Visibility.Visible
