name: issues-manager
on:
  issue_comment:
    types: [created]

jobs:
  issue_commented:
    runs-on: ubuntu-latest
    steps:
      - name: Custom Slash Commands
        uses: wow-actions/slash-commands@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: .github/slash-commands.yml

      - name: Pending Response Follow Up
        uses: siegerts/pending-response@v1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pending-response-label: needs-more-info
